appid: "331470"
publishedfileid: "3277289310"         
visibility: "2"               
title: "Дни нигде"
changenote: ""
previewfile: "deploy/avatar.png"
project_name: "din"
exclusions:
  - ".git"
  - ".github"
  - ".gitattributes"
  - ".gitignore"
  - ".vscode"
  - "scripts"
  - "steamcmd"
  - "build"
  - "README.md"
  - "deploy"
  - "exclusions.yml"
  - "markers.yml"